Priceless/Models/Student.cs
using System;
using System.Collections.Generic;

namespace Priceless.Models
{
    public class Student : Person
    {
        public string ParentName { get; set; }
        public string ParentPhone { get; set; }
        public string City { get; set; }
        public ICollection<Admission> Admissions { get; set; }
        public ICollection<Enrollment> Enrollments { get; set; }
    }
}

Priceless/Controllers/CoursesController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using System.Web.Helpers;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Priceless;
using Priceless.Models;
using Priceless.Models.Helpers;

namespace Priceless.Controllers
{
    public class CoursesController : Controller
    {
        private readonly PricelessContext _context;

        public CoursesController(PricelessContext context)
        {
            _context = context;
        }

        public async Task<IActionResult> Pages(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var course = await _context.Courses
                .Include(i => i.CourseAssignments).ThenInclude(i => i.Teacher)
                .Include(i => i.Enrollments).ThenInclude(i => i.Student)
                .Include(i => i.Exercises)
                .Include(i => i.Pages)
                .AsNoTracking().FirstOrDefaultAsync(m => m.Id == id);

            var teachers = course.CourseAssignments.Select(i => i.TeacherId);
            var students = course.Enrollments.Select(i => i.StudentId);
            if (course == null)
            {
                return NotFound();
            }

            string ids;
            if (HttpContext.Request.Cookies.TryGetValue("Id", out ids) && ids != null)
            {
                PersonCacheModel personCache = WebCache.Get("LoggedIn" + ids);
                if (personCache != null)
                {
                    if (personCache.Status == "Admin" || personCache.Status == "Curator" || teachers.Contains(personCache.Id)
                        || students.Contains(personCache.Id))
                    {
                        return View(course);
                    }
                    return StatusCode(StatusCodes.Status403Forbidden);
                }
                return StatusCode(StatusCodes.Status403Forbidden);
            }
            return StatusCode(StatusCodes.Status403Forbidden);
        }

        public async Task<IActionResult> Files(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var course = await _context.Courses
                .Include(i => i.CourseAssignments).ThenInclude(i => i.Teacher)
                .Include(i => i.Enrollments).ThenInclude(i => i.Student)
                .Include(i => i.Exercises)
                .Include(i => i.Pages)
                .AsNoTracking().FirstOrDefaultAsync(m => m.Id == id);

            var teachers = course.CourseAssignments.Select(i => i.TeacherId);
            var students = course.Enrollments.Select(i => i.StudentId);
            if (course == null)
            {
                return NotFound();
            }

            string ids;
            if (HttpContext.Request.Cookies.TryGetValue("Id", out ids) && ids != null)
            {
                PersonCacheModel personCache = WebCache.Get("LoggedIn" + ids);
                if (personCache != null)
                {
                    if (personCache.Status == "Admin" || personCache.Status == "Curator" || teachers.Contains(personCache.Id) || students.Contains(personCache.Id))
                    {
                        return View(course);
                    }
                    return StatusCode(StatusCodes.Status403Forbidden);
                }
                return StatusCode(StatusCodes.Status403Forbidden);
            }
            return StatusCode(StatusCodes.Status403Forbidden);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> EditFiles(int id, string formFile)
        {
            var course = await _context.Courses
                    .FirstOrDefaultAsync(m => m.Id == id);

            if (ModelState.IsValid)
            {
                string ids;
                PersonCacheModel personCache = null;
                if (HttpContext.Request.Cookies.TryGetValue("Id", out ids))
                {
                    personCache = WebCache.Get("LoggedIn" + ids);
                }

                var teachers = new HashSet<int>
                (_context.Teachers.Where(i => i.CourseAssignments.Where(c => c.CourseId == course.Id).Any()).Select(i => i.Id));
                if (personCache != null)
                {
                    var editor = _context.Teachers.FirstOrDefault(i => i.Id == personCache.Id);
                    if (editor != null)
                    {
                        if (teachers.Contains(editor.Id) || editor.Status == "Admin" || editor.Status == "Curator")
                        {
                            course.Uploads = formFile;

                            _context.Update(course);
                            await _context.SaveChangesAsync();

                            return RedirectToAction("Details", new { id = course.Id });
                        }
                        return StatusCode(StatusCodes.Status403Forbidden);
                    }
                    return StatusCode(StatusCodes.Status403Forbidden);
                }
                return StatusCode(StatusCodes.Status403Forbidden);
            }
            return RedirectToAction("Details", new { id = course.Id });
        }

        public async Task<IActionResult> Exercises(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var course = await _context.Courses
                .Include(i => i.CourseAssignments).ThenInclude(i => i.Teacher)
                .Include(i => i.Enrollments).ThenInclude(i => i.Student)
                .Include(i => i.Exercises)
                .Include(i => i.Pages)
                .AsNoTracking().FirstOrDefaultAsync(m => m.Id == id);

            var teachers = course.CourseAssignments.Select(i => i.TeacherId);
            var students = course.Enrollments.Select(i => i.StudentId);
            if (course == null)
            {
                return NotFound();
            }

            string ids;
            if (HttpContext.Request.Cookies.TryGetValue("Id", out ids) && ids != null)
            {
                PersonCacheModel personCache = WebCache.Get("LoggedIn" + ids);
                if (personCache != null)
                {
                    if (personCache.Status == "Admin" || personCache.Status == "Curator" || teachers.Contains(personCache.Id) || students.Contains(personCache.Id))
                    {
                        return View(course);
                    }
                    return StatusCode(StatusCodes.Status403Forbidden);
                }
                return StatusCode(StatusCodes.Status403Forbidden);
            }
            return StatusCode(StatusCodes.Status403Forbidden);
        }

        // GET: Courses
        public async Task<IActionResult> Index()
        {
            string ids;
            if (HttpContext.Request.Cookies.TryGetValue("Id", out ids) && ids != null)
            {
                PersonCacheModel personCache = WebCache.Get("LoggedIn" + ids);
                if (personCache != null)
                {
                    if (personCache.Status == "Admin" || personCache.Status == "Curator")
                    {
                        return View(await _context.Courses.ToListAsync());
                    }
                    return View(await _context.Courses.Where(i => i.CourseAssignments.Where(c => c.TeacherId == int.Parse(ids)).Any() || i.Enrollments.Where(c => c.StudentId == int.Parse(ids)).Any()).ToListAsync());
                }
                return StatusCode(StatusCodes.Status403Forbidden);
            }
            return StatusCode(StatusCodes.Status403Forbidden);
        }

        // GET: Courses/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var course = await _context.Courses
                .Include(i => i.CourseAssignments).ThenInclude(i => i.Teacher)
                .Include(i => i.Enrollments).ThenInclude(i => i.Student)
                .Include(i => i.Exercises)
                .Include(i => i.Pages)
                .AsNoTracking().FirstOrDefaultAsync(m => m.Id == id);

            var teachers = course.CourseAssignments.Select(i => i.TeacherId);
            var students = course.Enrollments.Select(i => i.StudentId);
            if (course == null)
            {
                return NotFound();
            }

            string ids;
            if (HttpContext.Request.Cookies.TryGetValue("Id", out ids) && ids != null)
            {
                PersonCacheModel personCache = WebCache.Get("LoggedIn" + ids);
                if (personCache != null)
                {
                    if (personCache.Status == "Admin" || personCache.Status == "Curator" || teachers.Contains(personCache.Id) || students.Contains(personCache.Id))
                    {
                        return View(course);
                    }
                    return StatusCode(StatusCodes.Status403Forbidden);
                }
                return StatusCode(StatusCodes.Status403Forbidden);
            }
            return StatusCode(StatusCodes.Status403Forbidden);
        }

        // GET: Courses/Create
        public IActionResult Create()
        {
            var course = new Course();
            course.CourseAssignments = new List<CourseAssignment>();
            string ids;
            HttpContext.Request.Cookies.TryGetValue("Id", out ids);
            course.Enrollments = new List<Enrollment>();
            PopulateAssignedStudentData(course);
            PopulateAssignedTeacherData(course, int.Parse(ids));
            return View();
        }

        // POST: Courses/Create

Priceless/Controllers/MajorsController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using System.Web.Helpers;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Priceless;
using Priceless.Models;
using Priceless.Models.Helpers;

namespace Priceless.Controllers
{
    public class MajorsController : Controller
    {
        private readonly PricelessContext _context;

        public MajorsController(PricelessContext context)
        {
            _context = context;
        }

        // GET: Majors
        public async Task<IActionResult> Index()
        {
            return View(await _context.Majors.ToListAsync());
        }

        // GET: Majors/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var major = await _context.Majors
                .FirstOrDefaultAsync(m => m.Id == id);
            if (major == null)
            {
                return NotFound();
            }

            return View(major);
        }

        // GET: Majors/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Majors/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Title,Image")] Major major)
        {
            if (ModelState.IsValid)
            {
                _context.Add(major);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(major);
        }

        // GET: Majors/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var major = await _context.Majors.FindAsync(id);
            if (major == null)
            {
                return NotFound();
            }

            return View(major);
        }

        // POST: Majors/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Title,Image")] Major major, bool deleteImage)
        {
            if (id != major.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                if (deleteImage)
                {
                    major.Image = null;
                }
                try
                {
                    _context.Update(major);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!MajorExists(major.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(major);
        }

        // GET: Majors/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var major = await _context.Majors
                .FirstOrDefaultAsync(m => m.Id == id);
            if (major == null)
            {
                return NotFound();
            }

            return View(major);
        }

        // POST: Majors/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var major = await _context.Majors
                .Include(i => i.Admissions)
                .Include(i => i.MajorAssignments)
                .SingleAsync(i => i.Id == id);

            _context.Majors.Remove(major);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool MajorExists(int id)
        {
            return _context.Majors.Any(e => e.Id == id);
        }
    }
}

Priceless/Views/Students/Delete.cshtml
@using Priceless.Models.Helpers;
@using System.Web.Helpers;

@model Priceless.Models.Student

@{
    ViewData["Title"] = "Delete";
    string ids;
    PersonCacheModel personCache = null;
    if (Context.Request.Cookies.TryGetValue("Id", out ids))
    {
        personCache = WebCache.Get("LoggedIn" + ids);
    }
    if (personCache != null)
    {
        if (personCache.Id == Model.Id)
        {
    <div class="container">
        <div class="row">
            <div class="col-md-2"></div>
            <div class="col-md-4">
                <div class="wsk-cp-product">
                    <div class="wsk-cp-img">
                        @{ if (Model.Image == null)
                            {
        <img src="~/img/default-user-icon.jpg" alt="courseImage" class="img-responsive" /> }
    else
    {
    <img src="@Model.Image" alt="courseImage" class="img-responsive" /> } }
                    </div>
                    <div class="wsk-cp-text">
                        <div class="title-product">
                            <h3>@Model.Name</h3>
                        </div>
                        <div class="description-prod">
                            <p>
                                Вы уверены что хотите удалить этот аккаунт?
                            </p>
                            <form asp-action="Delete">
                                <input type="hidden" asp-for="Id" />
                                <input type="submit" value="Удалить" class="btn btn-danger" /> |
                                <a asp-action="Index">Вернуться к списку</a>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
        }
        else
        {
            <div class="takeup">
<span class="text-danger">Пользователи могут изменять только свои аккаунты</span>
        </div>
            
        }
    }
    else
    {
        <div class="takeup">
<span class="text-danger"><a asp-action="Login" asp-controller="Home">Вы должны сперва войти в систему</a></span>
        </div>
        
    }
}

Priceless/Views/Students/Details.cshtml
@using Priceless.Models.Helpers;
@using System.Web.Helpers;

@model Priceless.Models.Student

@{
    ViewData["Title"] = "Details";
    var admissions = Model.Admissions;
    bool flag = false;
    string ids;
    PersonCacheModel personCache = null;
    if (Context.Request.Cookies.TryGetValue("Id", out ids))
    {
        personCache = WebCache.Get("LoggedIn" + ids);
    }
    if (personCache != null)
    {
        if (personCache.Status == "Admin" || personCache.Status == "Curator" || personCache.Id == Model.Id || (personCache.Status == "Admitted" & personCache.Role == "Teacher"))
        {
            flag = personCache.Id != Model.Id;
            <div class="row pad">
                <div class="col-md-6">
                    @{
                        if (Model.Status == "In process")
                        {
                            <h1>Статус заявки: В рассмотрении</h1>
                            <p>Для подробностей, обратитесь к разделу "Направления" внизу страницы</p>
                        }
                        else if (Model.Status == "Admitted")
                        {
                            <h1>Статус заявки: Принята</h1>
                            <p>Для подробностей, обратитесь к разделу "Направления" внизу страницы</p>
                        }
                        else if (Model.Status == "Rejected")
                        {
                            <h1>Статус заявки: Отклонена</h1>
                            <p>Для подробностей, обратитесь к разделу "Направления" внизу страницы</p>
                        }
                        else if (Model.Status == "Inactive")
                        {
                            <h1>Статус заявки: Не активна</h1>
                            <p>Чтобы активировать заявку, когда откроется регистрация на поток, зайдите в изменение профиля, выберите направления подготовки и отметьте галочку пересмотра заявки</p>
                            if (ViewBag.Open)
                            {
                                    <p>В настоящий момент регистрация открыта до @ViewBag.Stream.RegEnd</p>
                            }
                            else
                            {
                                if (ViewBag.Stream != null)
                            {
                                    <p>В настоящий момент регистрация закрыта. Регистрация на следующий поток начнется @ViewBag.Stream.RegStart</p>
                            } else
                            {
                                    <p>В настоящий момент регистрация закрыта. Регистрация на следующий поток скоро начнется</p>
                            }
                                
                            }
                            <p></p>
                        }
                    }
                </div>
            </div>
            <hr />
            <div class="row pad">
                <div class="col-md-6">
                    <h2>Personal information</h2>
                </div>
                @{
                    if (personCache.Id == Model.Id)
                    {
                        <div class="col-md-6">
                            <a asp-action="Edit" asp-route-id="@Model.Id">Изменить</a>
                        </div>
                    }
                }
                
            </div>
            <div class="row pad">
                    <div class="row">
                        <div class="col-md-6" style="text-align: center;">
                            @{
                                if (Model.Image != null)
                                {
                                    <img src="@Model.Image" alt="image" class="rounded-circle" style="width: 300px; height: 300px;"/>
                                }
                                else
                                {
                                    <img src="~/img/default-user-icon.jpg" alt="image" class="rounded-circle" style="width: 300px; height: 300px;"/>
                                }
                            }
                            <dl class="row">
                                <dt class="col-sm-6">
                                    Почта
                                </dt>
                                <dd class="col-sm-6">
                                    @Html.DisplayFor(model => model.Login)
                                </dd>
                                <dt class="col-sm-6">
                                    ФИО
                                </dt>
                                <dd class="col-sm-6">
                                    @Html.DisplayFor(model => model.Name)
                                </dd>
                                <dt class="col-sm-6">
                                    Номер телефона
                                </dt>
                                <dd class="col-sm-6">
                                    @Html.DisplayFor(model => model.Phone)
                                </dd>
                            </dl>
                        </div>
                        <div class="col-md-6" style="text-align: center;">
                            <dl class="row">
                                <dt class="col-sm-6">
                                    ФИО родителя
                                </dt>
                                <dd class="col-sm-6">
                                    @Html.DisplayFor(model => model.ParentName)
                                </dd>
                                <dt class="col-sm-6">
                                    Номер телефона родителя
                                </dt>
                                <dd class="col-sm-6">
                                    @Html.DisplayFor(model => model.ParentPhone)
                                </dd>
                                <dt class="col-sm-6">
                                    Город проживания
                                </dt>
                                <dd class="col-sm-6">
                                    @Html.DisplayFor(model => model.City)
                                </dd>
                                <dt class="col-sm-6">
                                    Класс
                                </dt>
                                <dd class="col-sm-6">
                                    @Html.DisplayFor(model => model.Grade)
                                </dd>
                                <dt class="col-sm-6">
                                    Ответ на первый вопрос
                                </dt>
                                <dd class="col-sm-6">
                                    @Html.DisplayFor(model => model.FirstQA)
                                </dd>
                                <dt class="col-sm-6">
                                    Ответ на второй вопрос
                                </dt>
                                <dd class="col-sm-6">
                                    @Html.DisplayFor(model => model.SecondQA)
                                </dd>
                                <dt class="col-sm-6">
                                    Ответ на третий вопрос
                                </dt>
                                <dd class="col-sm-6">
                                    @Html.DisplayFor(model => model.ThirdQA)
                                </dd>
                            </dl>
                        </div>
                    </div>
            </div>
            <hr />
            <div class="row pad bg-custom">
                <h2>Направления подготовки</h2>
            </div>
            <div class="row pad bg-custom">
                <div class="container">
    <div class="row">
        @{ int cnt2 = 0;

                        foreach (var admission in admissions)
                        {
                            cnt2++;
                            if (cnt2 % 3 == 1)
                            {
        @:</div><div class="row">
                }


<div class="col-md-4">
    <div class="wsk-cp-product">
        <div class="wsk-cp-img">
            @{ if (admission.Major.Image == null)
                {
<img src="~/img/major.png" alt="courseImage" class="img-responsive" /> }
else
{
<img src="@admission.Major.Image" alt="courseImage" class="img-responsive" /> } }
        </div>
        <div class="wsk-cp-text">
            <div class="title-product">
                <h3>@admission.Major.Title</h3>
            </div>
            <div class="description-prod">
                @{
                    if (admission.Status == "In process")
                    {
                        <h5>Статус заявки: В рассмотрении</h5>
                        if (flag)
                        {
                            <p>
                                <a asp-controller="Home" asp-action="Manage" asp-route-id="@Model.Id" asp-route-userId="@personCache.Id" asp-route-admit="true" asp-route-student="true" asp-route-majorId="@admission.MajorId">Принять</a>
                                |
                                <a asp-controller="Home" asp-action="Manage" asp-route-id="@Model.Id" asp-route-userId="@personCache.Id" asp-route-admit="false" asp-route-student="true" asp-route-majorId="@admission.MajorId">Отклонить</a>
                            </p>
                        }
                    }
                    else
                    {
                        if (admission.Status == "Admitted")
                        {
                            <h5>Статус заявки: Принята</h5>
                            <p>@admission.StatusComment</p>
                        }
                        else if (admission.Status == "Rejected")
                        {
                            <h5>Статус заявки: Отклонена</h5>
                            <p>@admission.StatusComment</p>
                        }
                        if (flag)
                        {
                            <p>
                                <a asp-controller="Home" asp-action="Manage" asp-route-id="@Model.Id" asp-route-userId="@personCache.Id" asp-route-admit="true" asp-route-student="true" asp-route-majorId="@admission.MajorId" asp-route-changeDecision="true">Изменить решение</a>
                            </p>
                        }
                    }
                }
                <a asp-controller="Majors" asp-action="Details" asp-route-id="@admission.Major.Id">Детали</a>
            </div>
        </div>
    </div>
</div> } }
    </div>

</div>

            </div>
            <hr />
            <div class="row pad">
                <h2>Курсы</h2>
            </div>
            <div class="row pad">
                <div class="container">
    <div class="row">
        @{
            var courses = Model.Enrollments.Select(i => i.Course);
            int cnt = 0;

            foreach (var course in courses)
            {
                cnt++;
                if (cnt % 3 == 1)
                {
@:</div><div class="row">
}


<div class="col-md-4">
    <div class="wsk-cp-product">
        <div class="wsk-cp-img">
            @{ if (course.Image == null)
                {
<img src="~/img/major.png" alt="courseImage" class="img-responsive" /> }
else
{
<img src="@course.Image" alt="courseImage" class="img-responsive" /> } }
        </div>
        <div class="wsk-cp-text">
            <div class="title-product">
                <h3>@course.Title</h3>
            </div>
            <div class="description-prod">
                <a asp-controller="Courses" asp-action="Details" asp-route-id="@course.Id" class="stretched-link"></a>
            </div>
        </div>
    </div>
</div> } }
    </div>

</div>
            </div>
        }
    else
        {
            <div class="takeup">
<span class="text-danger">Только студент и учителя могут просматривать эту страницу</span>
        </div>
            
        }
    }
    else
    {
        <div class="takeup">
<span class="text-danger"><a asp-action="Login" asp-controller="Home">Вы должны сперва войти в систему</a></span>
        </div>
        
    }
}